[2024-06-08T15:50:35.192+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T15:50:35.205+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pg_loader.load_clients manual__2024-06-08T15:50:34.338640+00:00 [queued]>
[2024-06-08T15:50:35.210+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pg_loader.load_clients manual__2024-06-08T15:50:34.338640+00:00 [queued]>
[2024-06-08T15:50:35.211+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T15:50:35.219+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_clients> on 2024-06-08 15:50:34.338640+00:00
[2024-06-08T15:50:35.222+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=921) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T15:50:35.223+0000] {standard_task_runner.py:63} INFO - Started process 922 to run task
[2024-06-08T15:50:35.223+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pg_loader', 'load_clients', 'manual__2024-06-08T15:50:34.338640+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/load_pg_dag.py', '--cfg-path', '/tmp/tmp_8460mmu']
[2024-06-08T15:50:35.224+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask load_clients
[2024-06-08T15:50:35.249+0000] {task_command.py:426} INFO - Running <TaskInstance: pg_loader.load_clients manual__2024-06-08T15:50:34.338640+00:00 [running]> on host 945bac6cf142
[2024-06-08T15:50:35.296+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pg_loader' AIRFLOW_CTX_TASK_ID='load_clients' AIRFLOW_CTX_EXECUTION_DATE='2024-06-08T15:50:34.338640+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-08T15:50:34.338640+00:00'
[2024-06-08T15:50:35.297+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T15:50:35.309+0000] {base.py:84} INFO - Using connection ID '***-etl' for task execution.
[2024-06-08T15:50:35.314+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T15:50:35.315+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_pg_dag.py", line 17, in load_clients
    src_clients = pg_cursor.fetchmany(CLIENTS_BATCH_SIZE)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.ProgrammingError: no results to fetch
[2024-06-08T15:50:35.321+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pg_loader, task_id=load_clients, run_id=manual__2024-06-08T15:50:34.338640+00:00, execution_date=20240608T155034, start_date=20240608T155035, end_date=20240608T155035
[2024-06-08T15:50:35.328+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 40 for task load_clients (no results to fetch; 922)
[2024-06-08T15:50:35.362+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-08T15:50:35.372+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T15:50:35.373+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
