[2024-06-08T15:42:14.758+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T15:42:14.771+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pg_loader.load_clients manual__2024-06-08T15:42:13.801267+00:00 [queued]>
[2024-06-08T15:42:14.775+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pg_loader.load_clients manual__2024-06-08T15:42:13.801267+00:00 [queued]>
[2024-06-08T15:42:14.776+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T15:42:14.783+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_clients> on 2024-06-08 15:42:13.801267+00:00
[2024-06-08T15:42:14.787+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=802) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T15:42:14.788+0000] {standard_task_runner.py:63} INFO - Started process 803 to run task
[2024-06-08T15:42:14.788+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pg_loader', 'load_clients', 'manual__2024-06-08T15:42:13.801267+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/load_pg_dag.py', '--cfg-path', '/tmp/tmpr56m8fjw']
[2024-06-08T15:42:14.788+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask load_clients
[2024-06-08T15:42:14.816+0000] {task_command.py:426} INFO - Running <TaskInstance: pg_loader.load_clients manual__2024-06-08T15:42:13.801267+00:00 [running]> on host 945bac6cf142
[2024-06-08T15:42:14.864+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pg_loader' AIRFLOW_CTX_TASK_ID='load_clients' AIRFLOW_CTX_EXECUTION_DATE='2024-06-08T15:42:13.801267+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-08T15:42:13.801267+00:00'
[2024-06-08T15:42:14.865+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T15:42:14.878+0000] {base.py:84} INFO - Using connection ID '***-etl' for task execution.
[2024-06-08T15:42:14.882+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T15:42:14.883+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_pg_dag.py", line 26, in load_clients
    (src_client.client_id, src_client.bonus_balance, src_client.category_id)
     ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'client_id'
[2024-06-08T15:42:14.890+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pg_loader, task_id=load_clients, run_id=manual__2024-06-08T15:42:13.801267+00:00, execution_date=20240608T154213, start_date=20240608T154214, end_date=20240608T154214
[2024-06-08T15:42:14.896+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 37 for task load_clients ('tuple' object has no attribute 'client_id'; 803)
[2024-06-08T15:42:14.926+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-08T15:42:14.936+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T15:42:14.938+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
