[2024-06-06T16:23:57.713+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T16:23:57.726+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongo_loader.load_clients manual__2024-06-06T16:23:57.315332+00:00 [queued]>
[2024-06-06T16:23:57.732+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongo_loader.load_clients manual__2024-06-06T16:23:57.315332+00:00 [queued]>
[2024-06-06T16:23:57.733+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-06T16:23:57.741+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_clients> on 2024-06-06 16:23:57.315332+00:00
[2024-06-06T16:23:57.744+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=443) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-06T16:23:57.745+0000] {standard_task_runner.py:63} INFO - Started process 444 to run task
[2024-06-06T16:23:57.745+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mongo_loader', 'load_clients', 'manual__2024-06-06T16:23:57.315332+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/load_mongo_dag.py', '--cfg-path', '/tmp/tmpncugo10r']
[2024-06-06T16:23:57.747+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask load_clients
[2024-06-06T16:23:57.774+0000] {task_command.py:426} INFO - Running <TaskInstance: mongo_loader.load_clients manual__2024-06-06T16:23:57.315332+00:00 [running]> on host 945bac6cf142
[2024-06-06T16:23:57.820+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mongo_loader' AIRFLOW_CTX_TASK_ID='load_clients' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T16:23:57.315332+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-06T16:23:57.315332+00:00'
[2024-06-06T16:23:57.822+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T16:23:57.835+0000] {base.py:84} INFO - Using connection ID 'mongo-etl' for task execution.
[2024-06-06T16:23:57.853+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T16:23:57.854+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_mongo_dag.py", line 14, in load_clients
    return jsonify(list(clients_cursor))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/celery/utils/serialization.py", line 249, in jsonify
    return [_jsonify(v) for v in obj]
            ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/celery/utils/serialization.py", line 252, in jsonify
    k: _jsonify(v, key=k) for k, v in obj.items()
       ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/celery/utils/serialization.py", line 261, in jsonify
    raise ValueError(
ValueError: Unsupported type: <class 'bson.objectid.ObjectId'> ObjectId('664ce399f542cb7c7020a31d') (parent: _id)
[2024-06-06T16:23:57.860+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=mongo_loader, task_id=load_clients, run_id=manual__2024-06-06T16:23:57.315332+00:00, execution_date=20240606T162357, start_date=20240606T162357, end_date=20240606T162357
[2024-06-06T16:23:57.868+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task load_clients (Unsupported type: <class 'bson.objectid.ObjectId'> ObjectId('664ce399f542cb7c7020a31d') (parent: _id); 444)
[2024-06-06T16:23:57.884+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-06T16:23:57.894+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-06T16:23:57.896+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
