[2024-06-06T16:27:50.002+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T16:27:50.014+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongo_loader.load_clients manual__2024-06-06T16:27:49.133636+00:00 [queued]>
[2024-06-06T16:27:50.019+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongo_loader.load_clients manual__2024-06-06T16:27:49.133636+00:00 [queued]>
[2024-06-06T16:27:50.020+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-06T16:27:50.028+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_clients> on 2024-06-06 16:27:49.133636+00:00
[2024-06-06T16:27:50.032+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=497) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-06T16:27:50.033+0000] {standard_task_runner.py:63} INFO - Started process 498 to run task
[2024-06-06T16:27:50.033+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mongo_loader', 'load_clients', 'manual__2024-06-06T16:27:49.133636+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/load_mongo_dag.py', '--cfg-path', '/tmp/tmp6mfpwc4n']
[2024-06-06T16:27:50.033+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask load_clients
[2024-06-06T16:27:50.060+0000] {task_command.py:426} INFO - Running <TaskInstance: mongo_loader.load_clients manual__2024-06-06T16:27:49.133636+00:00 [running]> on host 945bac6cf142
[2024-06-06T16:27:50.107+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mongo_loader' AIRFLOW_CTX_TASK_ID='load_clients' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T16:27:49.133636+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-06T16:27:49.133636+00:00'
[2024-06-06T16:27:50.109+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T16:27:50.121+0000] {base.py:84} INFO - Using connection ID 'mongo-etl' for task execution.
[2024-06-06T16:27:50.135+0000] {base.py:84} INFO - Using connection ID '***-etl' for task execution.
[2024-06-06T16:27:50.139+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T16:27:50.139+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_mongo_dag.py", line 19, in load_clients
    return json_utils.dumps(mongo_clients_cursor)
           ^^^^^^^^^^
NameError: name 'json_utils' is not defined. Did you mean: 'json_util'?
[2024-06-06T16:27:50.145+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=mongo_loader, task_id=load_clients, run_id=manual__2024-06-06T16:27:49.133636+00:00, execution_date=20240606T162749, start_date=20240606T162750, end_date=20240606T162750
[2024-06-06T16:27:50.152+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 32 for task load_clients (name 'json_utils' is not defined; 498)
[2024-06-06T16:27:50.172+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-06T16:27:50.182+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-06T16:27:50.183+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
